# Generated by Django 2.2 on 2019-05-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_path',
            field=models.ImageField(default='default.jpg', null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image_path',
            field=models.ImageField(default='default.jpg', null=True, upload_to='menu_images'),
        ),
        migrations.AlterField(
            model_name='order',
            name='create_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='create_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image_path',
            field=models.ImageField(default='default.jpg', null=True, upload_to='restaurant_images'),
        ),
    ]
