# Generated by Django 2.2 on 2019-05-03 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190503_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='extra_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='extra',
            name='extra_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image_path',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='menu_images'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='menus', through='main.User_menu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='menus',
            field=models.ManyToManyField(blank=True, null=True, related_name='orders', through='main.Order_menu', to='main.Menu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='receive_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_menu',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order_menu',
            name='status',
            field=models.CharField(blank=True, choices=[('preparing', 'preparing'), ('finished', 'finished')], default='preparing', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='close_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image_path',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='restaurant_images'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='open_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='res_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='restaurants', through='main.User_restaurant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='staff',
            name='res_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Restaurant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_path',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_images'),
        ),
    ]
