# Generated by Django 2.2 on 2019-05-03 11:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190503_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='menus', through='main.User_menu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='menus',
            field=models.ManyToManyField(blank=True, related_name='orders', through='main.Order_menu', to='main.Menu'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='restaurants', through='main.User_restaurant', to=settings.AUTH_USER_MODEL),
        ),
    ]
