# Generated by Django 2.2 on 2019-05-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190503_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
