# Generated by Django 2.2 on 2019-05-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190504_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image_path',
            field=models.ImageField(blank=True, default='menu_images/default.jpg', null=True, upload_to='menu_images'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image_path',
            field=models.ImageField(blank=True, default='restaurant_images/default.jpg', null=True, upload_to='restaurant_images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image_path',
            field=models.ImageField(blank=True, default='profile_images/default.jpg', null=True, upload_to='profile_images'),
        ),
    ]
