# Generated by Django 2.2 on 2019-05-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190504_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_path',
            field=models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='profile_images'),
        ),
    ]
