# Generated by Django 2.2 on 2019-05-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190504_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image_path',
            field=models.ImageField(blank=True, default='menu_images/default.png', null=True, upload_to='menu_images'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image_path',
            field=models.ImageField(blank=True, default='restaurant_images/default.png', null=True, upload_to='restaurant_images'),
        ),
    ]
