# Generated by Django 2.2 on 2019-05-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190504_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_menu',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
