# Generated by Django 2.2 on 2019-05-04 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='order_status',
        ),
    ]
