# Generated by Django 2.2 on 2019-05-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190506_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_path',
            field=models.ImageField(blank=True, default='user_images/default.png', null=True, upload_to='user_images'),
        ),
    ]
