# Generated by Django 2.2 on 2019-05-08 01:59

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190507_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='extra_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='receive_datetime',
            field=models.DateTimeField(null=True, validators=[main.models.validate_receive_datetime]),
        ),
    ]
